### ISSUE TITLE
Have trouble in install the Google cloud SDK with Python3.6

### ISSUE THREAD

**Issue by voladorange** [GoogleCloudPlatform/cloud-sdk-docker#117]
I have installed the Anaconda 3 with Python 3.6 in windows 10. It has wrong when I installed the Google cloud SDK by using the Interactive installer.

Here is the Error Message  during the installing:

Output folder: C:\Users\yyy96\AppData\Local\Google\Cloud SDK
Downloading Google Cloud SDK core.
Extracting Google Cloud SDK core.
Create Google Cloud SDK bat file: C:\Users\yyy96\AppData\Local\Google\Cloud SDK\cloud_env.bat
Installing components.
Welcome to the Google Cloud SDK!
ERROR: gcloud failed to load: 'ascii' codec can't decode byte 0xd3 in position 1: ordinal not in range(128)
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.calliope import base
    from googlecloudsdk.calliope import display
    from googlecloudsdk.calliope import display_taps
    from googlecloudsdk.core.resource import resource_printer_base
    from googlecloudsdk.core.resource import resource_projector
    from apitools.base.py import encoding as protorpc_encoding
    from apitools.base.py.base_api import *
    from apitools.base.py import http_wrapper
    from oauth2client.client import HttpAccessTokenRefreshError as TokenRefreshError  # noqa
    from oauth2client import crypt
    from oauth2client import _openssl_crypt
    from OpenSSL import crypto
    from OpenSSL import crypto, SSL
    from cryptography import x509
    from cryptography.x509.base import (
    from cryptography.x509.extensions import Extension, ExtensionType
    from asn1crypto.keys import PublicKeyInfo
    from ._elliptic_curve import (
    from ._int import inverse_mod
    from ._perf._big_num_ctypes import libcrypto
    libcrypto_path = find_library('crypto')
    fname = os.path.join(directory, name)
    result_path = result_path + p_path
This usually indicates corruption in your gcloud installation or problems with your Python interpreter.
Please verify that the following is the path to a working Python 2.7 executable:
    C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\python.exe
If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.
If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
Traceback (most recent call last):
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\\bin\bootstrapping\install.py", line 8, in <module>
    import bootstrapping
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\bootstrapping\bootstrapping.py", line 17, in <module>
    import oauth2client.contrib.gce as gce
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\third_party\oauth2client\contrib\gce.py", line 25, in <module>
    from oauth2client import client
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\third_party\oauth2client\client.py", line 51, in <module>
    from oauth2client import crypt
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\third_party\oauth2client\crypt.py", line 45, in <module>
    from oauth2client import _openssl_crypt
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\lib\third_party\oauth2client\_openssl_crypt.py", line 16, in <module>
    from OpenSSL import crypto
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
    from cryptography import x509
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\cryptography\x509\__init__.py", line 9, in <module>
    from cryptography.x509.base import (
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\cryptography\x509\extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "C:\Users\yyy96\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd3 in position 1: ordinal not in range(128)
Failed to install.

How can I deal with it?

**Comment by ahmetb** [comment]
Unfortunately this repo is about the gcloud Docker image. 

You can report your issue at https://cloud.google.com/support/docs/issue-trackers by clicking the Cloud SDK issues links.

**Comment by dondeivis** [comment]
CLOUDSDK_PYTHON ==[ruta donde tengas instalado el python]

**Comment by ahmetb** [comment]
This is not the issue tracker for Google Cloud SDK. Search for “google cloud issue trackers”.
