### ISSUE TITLE
NullPointerException in pubsub emulator

### ISSUE THREAD

**Issue by ThomWright** [GoogleCloudPlatform/cloud-sdk-docker#172]
Docker image tag: `google/cloud-sdk:252.0.0-alpine`
Client library: `@google-cloud/pubsub@0.28.1` from NPM

I occasionally see an NPE while using the pubsub emulator in my tests. The operations we do are pretty simple:

- check topic exists
- create topic
- create subscription
- publish messages

Let me know if there's any other useful debugging info I can provide.

Example logs and stack trace:

```
DEBUG: Running [gcloud.beta.emulators.pubsub.start] with arguments: [--data-dir: "/var/pubsub", --host-port: "<googlecloudsdk.calliope.arg_parsers.HostPort object at 0x7fcba2d583d0>", --log-http: "true", --user-output-enabled: "true", --verbosity: "debug"]
DEBUG: Found Cloud SDK root: /google-cloud-sdk
Executing: /google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=0.0.0.0 --port=8085
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] Jul 02, 2019 10:24:30 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] Jul 02, 2019 10:24:32 AM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
[pubsub] INFO: Applied Java 7 long hostname workaround.
[pubsub] Jul 02, 2019 10:24:32 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: Server started, listening on 8085
[pubsub] Jul 02, 2019 10:24:44 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[pubsub] INFO: Adding handler(s) to newly registered Channel.
[pubsub] Jul 02, 2019 10:24:44 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
[pubsub] Jul 02, 2019 10:31:57 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[pubsub] INFO: Adding handler(s) to newly registered Channel.
[pubsub] Jul 02, 2019 10:31:57 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[pubsub] INFO: Detected HTTP/2 connection.
[pubsub] Exception in thread "pool-1-thread-14" java.lang.NullPointerException
[pubsub] 	at java.util.concurrent.ConcurrentHashMap.hash(ConcurrentHashMap.java:333)
[pubsub] 	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:988)
[pubsub] 	at com.google.cloud.pubsub.testing.v1.FakePubsubServer$StreamingPullPusher.run(FakePubsubServer.java:865)
[pubsub] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
[pubsub] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
[pubsub] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pselden** [comment]
Did you figure this out? I have the same issue when running in a debian image.

**Comment by willfaris** [comment]
Closing this as this has nothing to do with the docker images but rather looks to be an issue with the pubsub emulator

**Comment by ThomWright** [comment]
> Closing this as this has nothing to do with the docker images but rather looks to be an issue with the pubsub emulator

Fair enough. How would I raise an issue on the pubsub emulator?
