### ISSUE TITLE
Intermittent Emulator Issue: Cannot connect to Cloud Datastore Emulator

### ISSUE THREAD

**Issue by speedplane** [GoogleCloudPlatform/cloud-sdk-docker#180]
I am running google app engine on the Cloud Datastore Emulator on my localhost, and I keep getting intermittent errors like the one below. Usually if I just wait a few seconds and try again, it works, but it's pretty frustrating to deal with. Any idea what is causing this?

### Starting the Emulator
I am starting the emulator with the following command:
```
Running:
"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd" beta emulators datastore start --host-port=localhost:8003 --data-dir="C:\Users\mes65\Documents\DAWork\.gaedata\datastore_gcl"
```

### Stack Trace
```
Traceback (most recent call last):
  File "C:\ProjFolder\django\core\handlers\base.py", line 90, in get_response
    response = middleware_method(request)
  File "C:\ProjFolder\updater\views.py", line 472, in process_request
    if request.user.is_anonymous():
  File "C:\ProjFolder\django\utils\functional.py", line 213, in inner
    self._setup()
  File "C:\ProjFolder\django\utils\functional.py", line 298, in _setup
    self._wrapped = self._setupfunc()
  File "C:\ProjFolder\django\contrib\auth\middleware.py", line 18, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\ProjFolder\django\contrib\auth\middleware.py", line 10, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\ProjFolder\django\contrib\auth\__init__.py", line 144, in get_user
    user = backend.get_user(user_id) or AnonymousUser()
  File "C:\ProjFolder\django\contrib\auth\backends.py", line 69, in get_user
    return UserModel._default_manager.get(pk=user_id)
  File "C:\ProjFolder\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\ProjFolder\django\db\models\query.py", line 301, in get
    num = len(clone)
  File "C:\ProjFolder\django\db\models\query.py", line 77, in __len__
    self._fetch_all()
  File "C:\ProjFolder\django\db\models\query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "C:\ProjFolder\django\db\models\query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "C:\ProjFolder\djangotoolbox\db\basecompiler.py", line 380, in results_iter
    for entity in results:
  File "C:\ProjFolder\djangoappengine\db\compiler.py", line 166, in fetch
    results = self.get_matching_pk(low_mark, high_mark)
  File "C:\ProjFolder\djangoappengine\db\compiler.py", line 401, in get_matching_pk
    results = [result for result in Get(self.included_pks, **config)
  File "C:\ProjFolder\djangoappengine\db\compiler.py", line 64, in Get
    return _do_retry(lambda: gae_Get(*args, **kwargs))
  File "C:\ProjFolder\djangoappengine\db\compiler.py", line 44, in _do_retry
    val = to_call()
  File "C:\ProjFolder\djangoappengine\db\compiler.py", line 64, in <lambda>
    return _do_retry(lambda: gae_Get(*args, **kwargs))
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\datastore.py", line 671, in Get
    return GetAsync(keys, **kwargs).get_result()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_stub_map.py", line 615, in get_result
    return self.__get_result_hook(self)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\datastore\datastore_rpc.py", line 1656, in __get_hook
    self.check_rpc_success(rpc)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\datastore\datastore_rpc.py", line 1377, in check_rpc_success
    rpc.check_success()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_stub_map.py", line 581, in check_success
    self.__rpc.CheckSuccess()
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_rpc.py", line 136, in CheckSuccess
    self._traceback)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\api\apiproxy_rpc.py", line 161, in _WaitImpl
    self.request, self.response)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 223, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\ext\remote_api\remote_api_stub.py", line 257, in _MakeRealSyncCall
    raise pickle.loads(response_pb.exception())
Exception: Cannot connect to Cloud Datastore Emulator on localhost:8003
```

### Versions
```
>gcloud version
Google Cloud SDK 261.0.0
app-engine-python 1.9.86
app-engine-python-extras 1.9.86
beta 2019.05.17
bq 2.0.47
cloud-datastore-emulator 2.1.0
core 2019.08.30
gsutil 4.42
kubectl 2019.08.23
```

**Comment by willfaris** [comment]
This project is for the Cloud SDK docker images.  To log a bug against the Emulators please use the public issue tracker.

https://issuetracker.google.com/issues/new?component=187143&template=800102
