### ISSUE TITLE
Error in 277.0.0 trying to copy from S3 to GS: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by de-code** [GoogleCloudPlatform/cloud-sdk-docker#196]
This was somewhat added as a [comment to another issue](https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/193#issuecomment-577649252) but seems worthy a separate issue:

```
Exception in thread Thread-37:B]                                                
Traceback (most recent call last):
  File "/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 632, in _PerformSimpleDownload
    key.get_contents_to_file(download_stream,
TypeError: get_contents_to_file() got an unexpected keyword argument 'hash_algs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/google-cloud-sdk/platform/gsutil/gslib/gcs_json_api.py", line 1537, in _PerformResumableUpload
    http_response = apitools_upload.StreamMedia(
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 1011, in StreamMedia
    return self.__StreamMedia(
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 957, in __StreamMedia
    response = send_func(self.stream.tell())
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 946, in CallSendMediaBody
    return self.__SendMediaBody(
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 1064, in __SendMediaBody
    return self.__SendMediaRequest(request, self.total_size)
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/transfer.py", line 1031, in __SendMediaRequest
    response = http_wrapper.MakeRequest(
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 355, in MakeRequest
    retry_func(ExceptionRetryArgs(http, http_request, e, retry,
  File "/google-cloud-sdk/platform/gsutil/gslib/utils/retry_util.py", line 84, in RetriesInDataTransferHandler
    http_wrapper.RethrowExceptionHandler(retry_args)
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 344, in MakeRequest
    return _MakeRequestNoRetry(
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/http_wrapper.py", line 393, in _MakeRequestNoRetry
    info, content = http.request(
  File "/google-cloud-sdk/platform/gsutil/gslib/gcs_json_media.py", line 308, in NewRequest
    return request_orig(uri,
  File "/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/transport.py", line 173, in new_request
    resp, content = request(orig_request_method, uri, method, body,
  File "/google-cloud-sdk/platform/gsutil/third_party/oauth2client/oauth2client/transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "/google-cloud-sdk/platform/gsutil/third_party/httplib2/python3/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/google-cloud-sdk/platform/gsutil/third_party/httplib2/python3/httplib2/__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/google-cloud-sdk/platform/gsutil/gslib/gcs_json_media.py", line 574, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/google-cloud-sdk/platform/gsutil/gslib/gcs_json_media.py", line 166, in _send_output
    self.send(message_body)
  File "/google-cloud-sdk/platform/gsutil/gslib/gcs_json_media.py", line 254, in send
    partial_buffer = full_buffer.read(self.GCS_JSON_BUFFER_SIZE)
  File "/google-cloud-sdk/platform/gsutil/third_party/apitools/apitools/base/py/stream_slice.py", line 71, in read
    data = self.__stream.read(read_size)
  File "/google-cloud-sdk/platform/gsutil/gslib/daisy_chain_wrapper.py", line 246, in read
    raise self.download_exception  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/google-cloud-sdk/platform/gsutil/gslib/daisy_chain_wrapper.py", line 202, in PerformDownload
    self.gsutil_api.GetObjectMedia(
  File "/google-cloud-sdk/platform/gsutil/gslib/cloud_api_delegator.py", line 340, in GetObjectMedia
    return self._GetApi(provider).GetObjectMedia(
  File "/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 576, in GetObjectMedia
    self._PerformSimpleDownload(
  File "/google-cloud-sdk/platform/gsutil/gslib/boto_translation.py", line 638, in _PerformSimpleDownload
    key.get_contents_to_file(download_stream,
  File "/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/key.py", line 1668, in get_contents_to_file
    self.get_file(fp, headers, cb, num_cb, torrent=torrent,
  File "/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/key.py", line 1497, in get_file
    self._get_file_internal(fp, headers=headers, cb=cb, num_cb=num_cb,
  File "/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/s3/key.py", line 1556, in _get_file_internal
    print_to_fd(six.ensure_binary(key_bytes), file=fp, end=b'')
  File "/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/utils.py", line 1206, in print_to_fd
    write_to_fd(file, data)
  File "/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/utils.py", line 1222, in write_to_fd
    fd.write(six.ensure_text(data))
  File "/google-cloud-sdk/platform/gsutil/gslib/vendored/boto/boto/vendored/six.py", line 901, in ensure_text
    return s.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Trying to copy from S3 to GS I am getting the following error using 277.0.0 or 278.0.0. I  tried basically all variations, no suffix, `-slim`, `-alpine`, `-debian_component_based`.

Whereas it was working locally and with a lower version (e.g. `276.0.0-alpine`). It seemed that gsutil reported the same version though.

```console
$ gsutil --version
gsutil version: 4.47
```

**Comment by HagaSpa** [comment]
The same problem occurs when rsyncing a gz file with the latest aline tag.

But `276.0.0-alpine` did not occures.

**Comment by willfaris** [comment]
I believe gsutil has fixed this issue, can you still reproduce the issue?

**Comment by willfaris** [comment]
Please re-open if this is still an issue.
