### ISSUE TITLE
Bigtable emulator connection fails when using with docker-compose

### ISSUE THREAD

**Issue by seakayone** [GoogleCloudPlatform/cloud-sdk-docker#253]
I have setup a [minmal case ](https://github.com/seakayone/python-gcloud-emulators-docker-compose) which demonstrates my problem with using the bigtable emulator setup as a docker container started with docker compose.

Starting the emulators manually works fine

```console
gcloud beta emulators bigtable start
$(gcloud beta emulators bigtable env-init)
python gcloud-emulators-docker-python/main.py  

BIGTABLE_EMULATOR_HOST: localhost:8086
Ensuring the some-table table exists.
Creating the some-table table.
Creating column family cf1 with Max Version GC rule...
Deleting the some-table table.
```

But when running the same Python code running with emulators started with docker compose it fails with `503 failed to connect to all addresses` from the the google-cloud-bigtable Python client.

Starting the emulators as docker container:

```console
docker-compose up &
export BIGTABLE_EMULATOR_HOST=localhost:8086
python gcloud-emulators-docker-python/main.py  

// output from docker compose
[+] Running 1/0
 ⠿ Container gcloud-emulators-docker-python_bigtable_1  Created                                                                                        0.1s
Attaching to bigtable_1
bigtable_1  | Executing: /google-cloud-sdk/platform/bigtable-emulator/cbtemulator --host=localhost --port=8086
bigtable_1  | [bigtable] Cloud Bigtable emulator running on 127.0.0.1:8086

// output from python process
BIGTABLE_EMULATOR_HOST127.0.0.1:8086
Ensuring the some-table table exists.
Creating the some-table table.
Creating column family cf1 with Max Version GC rule...
Traceback (most recent call last):
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1622107536.009954000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3009,"referenced_errors":[{"created":"@1622107521.031831000","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":398,"grpc_status":14}]}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/api_core/retry.py", line 188, in retry_target
    return target()
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kleinboelting/git/one-platform-rtl/gcloud-emulators-docker-python/gcloud-emulators-docker-python/main.py", line 35, in <module>
    main()
  File "/Users/kleinboelting/git/one-platform-rtl/gcloud-emulators-docker-python/gcloud-emulators-docker-python/main.py", line 25, in main
    if not table.exists():
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/cloud/bigtable/table.py", line 415, in exists
    table_client.get_table(request={"name": self.name, "view": VIEW_NAME_ONLY})
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/cloud/bigtable_admin_v2/services/bigtable_table_admin/client.py", line 828, in get_table
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/api_core/retry.py", line 285, in retry_wrapped_func
    return retry_target(
  File "/Users/kleinboelting/.virtualenvs/gcloud-emulators-docker-python/lib/python3.8/site-packages/google/api_core/retry.py", line 203, in retry_target
    six.raise_from(
  File "<string>", line 3, in raise_from
google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x10926a3a0>, name: "projects/some-project-id/instances/some-instance-id/tables/some-table"
view: NAME_ONLY
, metadata=[('x-goog-request-params', 'name=projects/some-project-id/instances/some-instance-id/tables/some-table'), ('x-goog-api-client', 'gl-python/3.8.9 grpc/1.38.0 gax/1.28.0')]), last exception: 503 failed to connect to all addresses

Process finished with exit code 1
```

I would have expected the same code to work with the emulators in the docker container. Even if I set ` export BIGTABLE_EMULATOR_HOST=127.0.0.1:8086` it fails with the same reason.

**Comment by seakayone** [comment]
I have been able to fix the above issue as persent in commit 4c787ef363 so that a process running on the host is now able to connect to the emulator in a docker container. The fix is adding a `--port` argument to the startup command: `gcloud beta emulators bigtable start --host-port=0.0.0.0:8086`.

I am still unable to establish communication between docker containers. By default docker compose sets up a single network in which the emulator and the python process run in separate containers. And still I am unable to establish communication.

This is how the case fails when using `gcloud beta emulators bigtable start --host-port=bigtable:8086` or `gcloud beta emulators bigtable start --host-port=0.0.0.0:8086` used as startup command for the emulator container.
```
docker compose up                                                                                                                                                                        gcloud-emulators-docker-python/git/main !+

[+] Running 2/0
 ⠿ Container gcloud-emulators-docker-python_bigtable_1   Created                                                                                                                                                                                                  0.0s
 ⠿ Container gcloud-emulators-docker-python_pythonapp_1  Created                                                                                                                                                                                                  0.0s
Attaching to bigtable_1, pythonapp_1

bigtable_1   | Executing: /google-cloud-sdk/platform/bigtable-emulator/cbtemulator --host=0.0.0.0 --port=8086
bigtable_1   | [bigtable] Cloud Bigtable emulator running on [::]:8086

pythonapp_1  | BIGTABLE_EMULATOR_HOST: bigtable:8086
pythonapp_1  | Ensuring the some-table table exists.
pythonapp_1  | Creating the some-table table.
pythonapp_1  | Creating column family cf1 with Max Version GC rule...
pythonapp_1  | Traceback (most recent call last):
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
pythonapp_1  |     return callable_(*args, **kwargs)
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
pythonapp_1  |     return _end_unary_response_blocking(state, call, False, None)
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
pythonapp_1  |     raise _InactiveRpcError(state)
pythonapp_1  | grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
pythonapp_1  |  status = StatusCode.UNAVAILABLE
pythonapp_1  |  details = "failed to connect to all addresses"
pythonapp_1  |  debug_error_string = "{"created":"@1622112486.781421900","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1622112471.707069600","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
pythonapp_1  | >
pythonapp_1  |
pythonapp_1  | The above exception was the direct cause of the following exception:
pythonapp_1  |
pythonapp_1  | Traceback (most recent call last):
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 188, in retry_target
pythonapp_1  |     return target()
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
pythonapp_1  |     six.raise_from(exceptions.from_grpc_error(exc), exc)
pythonapp_1  |   File "<string>", line 3, in raise_from
pythonapp_1  | google.api_core.exceptions.ServiceUnavailable: 503 failed to connect to all addresses
pythonapp_1  |
pythonapp_1  | The above exception was the direct cause of the following exception:
pythonapp_1  |
pythonapp_1  | Traceback (most recent call last):
pythonapp_1  |   File "/app/main.py", line 35, in <module>
pythonapp_1  |     main()
pythonapp_1  |   File "/app/main.py", line 25, in main
pythonapp_1  |     if not table.exists():
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/cloud/bigtable/table.py", line 415, in exists
pythonapp_1  |     table_client.get_table(request={"name": self.name, "view": VIEW_NAME_ONLY})
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/cloud/bigtable_admin_v2/services/bigtable_table_admin/client.py", line 828, in get_table
pythonapp_1  |     response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
pythonapp_1  |     return wrapped_func(*args, **kwargs)
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 285, in retry_wrapped_func
pythonapp_1  |     return retry_target(
pythonapp_1  |   File "/usr/local/lib/python3.9/site-packages/google/api_core/retry.py", line 203, in retry_target
pythonapp_1  |     six.raise_from(
pythonapp_1  |   File "<string>", line 3, in raise_from
pythonapp_1  | google.api_core.exceptions.RetryError: Deadline of 60.0s exceeded while calling functools.partial(<function _wrap_unary_errors.<locals>.error_remapped_callable at 0x7f07f9d65af0>, name: "projects/some-project-id/instances/some-instance-id/tables/some-table"
pythonapp_1  | view: NAME_ONLY
pythonapp_1  | , metadata=[('x-goog-request-params', 'name=projects/some-project-id/instances/some-instance-id/tables/some-table'), ('x-goog-api-client', 'gl-python/3.9.5 grpc/1.38.0 gax/1.28.0')]), last exception: 503 failed to connect to all addresses
pythonapp_1 exited with code 1
```

**Comment by ntaylorwss** [comment]
Has anyone found a solution to this? Currently struggling with the exact same problem.

**Comment by ntaylorwss** [comment]
Update: I was able to solve the problem.

When this environment variable is set, the Client's method `_emulator_channel` produces a channel by which requests are made. The problem here is that the **emulator channel is a secure channel, meaning it uses https**. Https requests to the bigtable emulator container fail with a 503, because it is serving http. The solution (or at least, my solution) was to replace the `_emulator_channel` method of the Client with one that produces a `grpc.insecure_channel`, where the target is the `BIGTABLE_EMULATOR_HOST` variable.

```
import os
import grpc
from google.cloud import bigtable

client = bigtable.Client(admin=True)

def replace_emulator_channel_fn(transport, options):
    return grpc.insecure_channel(target=os.environ["BIGTABLE_EMULATOR_HOST"])

client._emulator_channel = replace_emulator_channel_fn

client.instance("myinstance").table("mytable").create()

print(client.instance("myinstance").list_tables()[0].name)
projects/myproject/instances/myinstance/tables/mytable
```

**Comment by willfaris** [comment]
Closing the issue because of ntaylorwss's comment

**Comment by rem-lag** [comment]
Incase anyone comes across this in the future and is still having a problem after implementing the above solution, what worked for me was setting the host to the name of the container
ie
your `docker-compose.yml` entry should look something like 
```yaml
  btemulator:
    build:
      context: .
      dockerfile: Dockerfile.bt-emulator
    command: gcloud beta emulators bigtable start --host-port=btemulator:8086
    env_file: env.tests
    networks:
      default: {}
    ports:
    - 8086:8086
```
with the environment var set to `BIGTABLE_EMULATOR_HOST=btemulator:8086`

**Comment by rem-lag** [comment]
when I pushed this to jenkins It ended up being unable to either connect or start the emulator on a valid host again even though it was fine locally

What ended up working was was creating a small shell script and adding a `COPY` in Dockerfile.btemulator to pick it up
```bash
#!/bin/bash
HP="${HOSTNAME}:8086"

gcloud beta emulators bigtable start --host-port=$HP
```
then instead of the `command` in my example yaml above I set
```yaml
    entrypoint: bash ./btemulator.sh
```
Leaving the env var in my `env.tests` as `BIGTABLE_EMULATOR_HOST=btemulator:8086` still was fine, the problem was on setting the host for the emulator itself. 

No idea how universal this solution is but thought I should be complete about what worked
