### ISSUE TITLE
Datastore emulator with `--use-firestore-in-datastore-mode` doesn't start

### ISSUE THREAD

**Issue by s-takehana** [GoogleCloudPlatform/cloud-sdk-docker#275]
`CLOUD_SDK_VERSION` `387.0.0`

- Dockerfile
```dockerfile
FROM google/cloud-sdk:emulators
VOLUME ["/opt/data"]
CMD gcloud beta emulators datastore start \
    --data-dir=/opt/data \
    --host-port=$DATASTORE_LISTEN_ADDRESS \
    --project=$DATASTORE_PROJECT_ID \
    --use-firestore-in-datastore-mode
```

- Log
```
Executing: /google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator create --project_id=***** /opt/data
[datastore] May 25, 2022 2:12:23 AM com.google.cloud.datastore.emulator.CloudDatastore$CreateAction$1 apply
[datastore] INFO: Provided project_id to Cloud Datastore emulator create command, which is no longer necessary.
[datastore] Created new Cloud Datastore project in '/opt/data'.
Executing: /google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=0.0.0.0 --port=8081 --store_on_disk=True --allow_remote_shutdown --firestore_in_datastore_mode /opt/data
[datastore] May 25, 2022 2:12:24 AM com.google.cloud.datastore.emulator.CloudDatastore$FakeDatastoreAction$9 apply
[datastore] INFO: Provided --allow_remote_shutdown to start command which is no longer necessary.
[datastore] Exception in thread "main" java.lang.NullPointerException
[datastore]  at com.google.common.base.Ascii.equalsIgnoreCase(Ascii.java:656)
[datastore]  at com.google.cloud.datastore.emulator.cli.EmulatorOption.getValueAsBoolean(EmulatorOption.java:65)
[datastore]  at com.google.cloud.datastore.emulator.CloudDatastore$FakeDatastoreAction$14.apply(CloudDatastore.java:342)
[datastore]  at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:56)
[datastore]  at com.google.cloud.datastore.emulator.CloudDatastore.run(CloudDatastore.java:730)
[datastore]  at com.google.cloud.datastore.emulator.CloudDatastore.main(CloudDatastore.java:689)
```

**Comment by dy-dx** [comment]
@s-takehana In the latest release of gcloud sdk (388.0.0), it looks like they've fixed this: https://cloud.google.com/sdk/docs/release-notes#38800_2022-06-01

![image](https://user-images.githubusercontent.com/1074881/172415847-a3edc139-7876-4992-8f23-ccd6c2da5b20.png)

**Comment by s-takehana** [comment]
@dy-dx Thank you.
